# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f9e58a50b5149276159251a7e468ff4b5c0f449c8c06a9d07efa4fb669e59e5686fde433971aab4696e560dc6fbbeb676b3cda9f162f9824ef537778fae10c

test:
  secret_key_base: 5efe4a24d717cc581777abd69c973156f540c1b1aca5d245bbdf2300a041fe52f93463904adfec56dc585729d8a09f0b37334e7f6c234691769b5148ef0f1ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
